name: Deploy

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    concurrency: deployment

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{ secrets.AMAZON_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AMAZON_SECRET_KEY }}
    - uses: google-github-actions/setup-gcloud@v0
      with:
        version: 'latest'
        project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_SERVICE_KEY }}
        export_default_credentials: true
    - run: npm ci
    - run: make build
    - run: make deploy
